export const todoItems = [
    {'id': '1', 'content': '页面基本样式调整'},
    {'id': '2', 'content': '左侧栏目录层级样式'},
    {'id': '3', 'content': 'content部分样式'},
    {'id': '4', 'content': 'nav样式'},
    {'id': '5', 'content': 'input,button,*:hover'},
    {'id': '6', 'content': 'Accessibility'},
    {'id': '7', 'content': 'svg是什么,'},
    {'id': '8', 'content': 'path里面的d是什么？'},
    {'id': '9', 'content': '各种@method'},
    {'id': '10', 'content': 'express.js学习'},
    {'id': '11', 'content': 'workflow'},
    {'id': '12', 'content': 'font'},
    {'id': '13', 'content': 'css'},
    {'id': '14', 'content': 'font'},
    {'id': '15', 'content': 'by'},
    {'id': '16', 'content': 'language'},
    {'id': '17', 'content': 'nav'},
    {'id': '18', 'content': 'layout'},
    {'id': '19', 'content': 'nav'},
    {'id': '20', 'content': 'input'},
    {'id': '21', 'content': 'nav'},
    {'id': '22', 'content': 'button'},
    {'id': '23', 'content': 'left'},
    {'id': '24', 'content': 'aside'},
    {'id': '25', 'content': 'layout'},
    {'id': '26', 'content': 'left'},
    {'id': '27', 'content': 'aside'},
    {'id': '28', 'content': 'basic'},
    {'id': '29', 'content': 'style'},
    {'id': '30', 'content': 'left'},
    {'id': '31', 'content': 'aside'},
    {'id': '32', 'content': 'input'},
    {'id': '33', 'content': 'left'},
    {'id': '34', 'content': 'aside'},
    {'id': '35', 'content': 'button'},
    {'id': '36', 'content': 'main'},
    {'id': '37', 'content': 'content'},
    {'id': '38', 'content': 'layout'},
    {'id': '39', 'content': 'main'},
    {'id': '40', 'content': 'content'},
    {'id': '41', 'content': 'scrollbar'},
    {'id': '42', 'content': 'main'},
    {'id': '43', 'content': 'content'},
    {'id': '44', 'content': 'check'},
    {'id': '45', 'content': 'box'},
    {'id': '46', 'content': 'footer'},
    {'id': '47', 'content': 'design'},
    {'id': '48', 'content': 'footer'},
    {'id': '49', 'content': 'html'},
    {'id': '50', 'content': 'footer'},
    {'id': '51', 'content': 'layout'},
    {'id': '52', 'content': 'footer'},
    {'id': '53', 'content': 'basic'},
    {'id': '54', 'content': 'server'},
    {'id': '55', 'content': 'monitor'},
    {'id': '56', 'content': 'footer'},
    {'id': '57', 'content': 'page'},
    {'id': '58', 'content': 'load'},
    {'id': '59', 'content': 'timer'},
    {'id': '60', 'content': 'footer'},
    {'id': '61', 'content': 'event'},
    {'id': '62', 'content': 'line'},
    {'id': '63', 'content': 'footer'},
    {'id': '64', 'content': 'random'},
    {'id': '65', 'content': 'talk'},
    {'id': '66', 'content': 'responsive'},
    {'id': '67', 'content': 'web'},
    {'id': '68', 'content': 'design'},
    {'id': '69', 'content': '要 做的事情可不少'},
    {'id': '70', 'content': '重点是不要沮丧'},
    {'id': '71', 'content': '你在很短的时间里学会了很多东西'},
    {'id': '72', 'content': '而且大多都是新知识'},
    {'id': '73', 'content': '自救'},
    {'id': '74', 'content': '自强'},
    {'id': '75', 'content': '自渡'},
    {'id': '76', 'content': '突然又有了一个单词本的点子'},
    {'id': '77', 'content': '背景一点透视，远景图片'},
    {'id': '78', 'content': 'expressJS高级'},
    {'id': '79', 'content': 'expressJS+mongodb+react'},
    {'id': '80', 'content': '远程桌面协议'}]

export const projects = [
    {"id": 1, "name": "golang练习", "count": 666},
    {"id": 2, "name": "应用层协议", "count": 33},
    {"id": 3, "name": "TODO", "count": 10},
    {"id": 4, "name": "Timeline", "count": 5},
    {"id": 5, "name": "安全", "count": 3}
]

export const monitorInfo = {
    pageLoadCost: 1.5,
    dbInfo: {dbQueryCount: 4, dbCost: 600},
    serverInfo: {cpu: 15, memory: 17, disk: 50},
    currentEvent: "mark task as done in 2022-4-19 15:12:11"
}
